// <auto-generated />
using System;
using DeathMahjong.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeathMahjong.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722114511_AddWindCountToCompletedGamePlayers")]
    partial class AddWindCountToCompletedGamePlayers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeathMahjong.Api.Data.Entities.CompletedGameEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("DrawnTileCount")
                        .HasColumnType("integer");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("EndReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FullDeckMode")
                        .HasColumnType("boolean");

                    b.Property<bool>("HardCoreMode")
                        .HasColumnType("boolean");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalSips")
                        .HasColumnType("integer");

                    b.Property<string>("WinnerPlayerId")
                        .HasColumnType("text");

                    b.Property<string>("WinnerPlayerName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CompletedGames");
                });

            modelBuilder.Entity("DeathMahjong.Api.Data.Entities.CompletedGamePlayerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CompletedGameId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DragonCount")
                        .HasColumnType("integer");

                    b.Property<int>("FinalRank")
                        .HasColumnType("integer");

                    b.Property<int?>("LatestSips")
                        .HasColumnType("integer");

                    b.Property<string>("LatestTileName")
                        .HasColumnType("text");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalSips")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("WindCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompletedGameId");

                    b.ToTable("CompletedGamePlayers");
                });

            modelBuilder.Entity("DeathMahjong.Api.Data.Entities.GameMoveEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Drinks")
                        .HasColumnType("integer");

                    b.Property<string>("GameRoomId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TileValue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameRoomId");

                    b.ToTable("GameMoves");
                });

            modelBuilder.Entity("DeathMahjong.Api.Data.Entities.GamePlayerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameRoomId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameRoomId");

                    b.ToTable("GamePlayers");
                });

            modelBuilder.Entity("DeathMahjong.Api.Data.Entities.GameRoomEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("CurrentPlayerIndex")
                        .HasColumnType("integer");

                    b.Property<string>("EndReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndedByPlayerId")
                        .HasColumnType("text");

                    b.Property<bool>("FullDeckMode")
                        .HasColumnType("boolean");

                    b.Property<bool>("HardCoreMode")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasEnded")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasStarted")
                        .HasColumnType("boolean");

                    b.Property<string>("HostPlayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.ToTable("GameRooms");
                });

            modelBuilder.Entity("DeathMahjong.Api.Data.Entities.GameTileEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("GameRoomId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDrawable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDrawn")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.Property<int>("Z")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameRoomId");

                    b.ToTable("GameTiles");
                });

            modelBuilder.Entity("DeathMahjong.Api.Data.Entities.CompletedGamePlayerEntity", b =>
                {
                    b.HasOne("DeathMahjong.Api.Data.Entities.CompletedGameEntity", "CompletedGame")
                        .WithMany("Players")
                        .HasForeignKey("CompletedGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletedGame");
                });

            modelBuilder.Entity("DeathMahjong.Api.Data.Entities.GameMoveEntity", b =>
                {
                    b.HasOne("DeathMahjong.Api.Data.Entities.GameRoomEntity", "GameRoom")
                        .WithMany("Moves")
                        .HasForeignKey("GameRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameRoom");
                });

            modelBuilder.Entity("DeathMahjong.Api.Data.Entities.GamePlayerEntity", b =>
                {
                    b.HasOne("DeathMahjong.Api.Data.Entities.GameRoomEntity", "GameRoom")
                        .WithMany("Players")
                        .HasForeignKey("GameRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameRoom");
                });

            modelBuilder.Entity("DeathMahjong.Api.Data.Entities.GameTileEntity", b =>
                {
                    b.HasOne("DeathMahjong.Api.Data.Entities.GameRoomEntity", "GameRoom")
                        .WithMany("Tiles")
                        .HasForeignKey("GameRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameRoom");
                });

            modelBuilder.Entity("DeathMahjong.Api.Data.Entities.CompletedGameEntity", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("DeathMahjong.Api.Data.Entities.GameRoomEntity", b =>
                {
                    b.Navigation("Moves");

                    b.Navigation("Players");

                    b.Navigation("Tiles");
                });
#pragma warning restore 612, 618
        }
    }
}
